Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -54,7 +54,7 @@ jobs:
       # Step 3: Run the Docker container
       - name: Run container for testing
         run: |
-          docker run -d -p 4000:3000 kishorbabum9/my-test-docker:host
+          docker run -d -p 5000:3000 kishorbabum9/my-test-docker:host
 
       # Step 4: Wait for the application to start
       - name: Wait for application to start
@@ -68,7 +68,7 @@ jobs:
       # Step 6: Test the application
       - name: Test application
         run: |
-          curl --fail http://localhost:4000 || exit 1  # Fail if the app doesn't respond
+          curl --fail http://localhost:5000 || exit 1  # Fail if the app doesn't respond
 
   deploy:
     runs-on: ubuntu-latest
